apiVersion: v1
kind: Pod
metadata:
  name: busybox1
  labels:
    aks-lab: headless
spec:
  hostname: busybox-1
  subdomain: headless-svc
  containers:
  - image: busybox:1.28
    command:
      - sleep
      - "3600"
    name: busybox
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox2
  labels:
    aks-lab: headless
spec:
  hostname: busybox-2
  subdomain: headless-svc
  containers:
  - image: busybox:1.28
    command:
      - sleep
      - "3600"
    name: busybox
    readinessProbe:
      exec:
        command:
        - exit
        - "1"
      initialDelaySeconds: 5
      periodSeconds: 5
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox3
  labels:
    aks-lab: headless
spec:
  hostname: busybox-3
  subdomain: wrong-svc
  containers:
  - image: busybox:1.28
    command:
      - sleep
      - "3600"
    name: busybox