apiVersion: v1
kind: Pod
metadata:
  name: 6-none
  namespace: default
  labels:
    aks-lab: dnspolicy
spec:
  containers:
  - name: dnsutils
    image: gcr.io/kubernetes-e2e-test-images/dnsutils:1.3
    command:
      - sleep
      - "86400"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
  dnsPolicy: None
  dnsConfig:
    nameservers:
    - 1.1.1.1