apiVersion: v1
kind: Pod
metadata:
  name: 7-dnsconfig-dnspolicy
  namespace: default
  labels:
    aks-lab: dnspolicy
spec:
  containers:
  - name: dnsutils
    image: gcr.io/kubernetes-e2e-test-images/dnsutils:1.3
    command:
      - sleep
      - "86400"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
  dnsPolicy: ClusterFirst
  dnsConfig:
    nameservers:
    - 1.1.1.1
    searches:
    - my.dns.search.suffix
    options:
    - name: single-request-reopen